import "./globals.css";

import Nav from "../components/nav";

export const metadata = {
  title: "Padel Vida",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
            <div className="holder">
                <img src="/img/logopadel.png" width="100" alt="padelvida"/>
                <h1>Padel Vida</h1>
            </div>
        </header>
        <Nav/>   
        {children}        
        <footer>
          <p>Derechos reservados.</p>
        </footer>
      </body>
    </html>
  );
}
